language: python
python:
- '3.6'
- '3.7'
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
- bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip pytest numpy
  pandas>=0.18.1
- source activate test-environment
- python setup.py install
script: python -m pytest test/
deploy:
  provider: pypi
  user: TokenNobody
  password:
    secure: XazMtrRpb6i/jtdeBIDV5mWZNQr2dPlmspgF/qqt9AbZRCu/Y28DaI/12KGSFgVJc2lzREp+cxKNq60bDT8mB3t0+YtYeHsmQXawInyXAFACfmRI5/nigiYLMhQ1OV/RHtXQcXeHJF1MbKeF2WjWdBKh9m9cBi5NVxGot/knGOALkwyiPG4Ykf5fVD4bCeJTkdrBav/XLYqYPntpw6GT0PA8yvt3E1lQfL+uTV8+ZcwsqXh8ebWNI0aU86lurE6b1cJn6xpTZYzSqiJqHuikCZC7alqd311kpm/sKuHMb2V9tKiHiJFN7fcKfdaVuAjQE22Tc7R7uC2ph9tBvL8xHnzi48Wj9Ri5QYLATN2u28d3rkCS+zN+tC3MT9bjDcyuqPdbx3Sx5bFJC6P0HFcof5lpnan80TW4VQSM2GV8rqwPgm0kLi0k/DG5yvRWecNdlvvCDZ5e6M9eiOcer9guimDYITtQCfuiUZLUbzgw+u7QE3jY9Exnv7Ekdi150Zd+ubPS+yU1ZG5tgB2ijw7n2bTxEy77d6Zm0quDnQ6gVBi7STp2si3397TTQH/nV+eaX51VOxTufZXDW0eiaVoRhH32xUllhFeAzJSezAVJ0WuLEuSLXGkxep7VNofK0Kyjxg4S2ED41lV7LtucdQe7L/LlGTfmYCgzSDaDW98CqIM=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: kieferk/dfply
    branch: master
